---
driver:
  name: hyperv
  parent_vhd_folder: 'E:/ImageFactory/Share'
  memory_startup_bytes: 1073741824

transport:
  name: winrm

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7

platforms:
  - name: windows_2012r2_wmf4
    driver:
      parent_vhd_name: 'WindowsServer2012R2.vhdx'
  - name: windows_2012r2_wmf5
    driver:
      parent_vhd_name: 'WindowsServer2012R2-wmf5.vhdx'

verifier:
  name: pester

suites:
  - name: dsc
    includes:
      - windows_2012r2_wmf5
    provisioner:
      name: dsc
      configuration_name: SimpleWebserver
      configuration_script: simple_webserver.ps1
      configuration_data_variable: ConfigurationData
      dsc_local_configuration_manager_version: wmf5
      dsc_local_configuration_manager:
        action_after_reboot: 'StopConfiguration'
        allow_module_overwrite: false
        certificate_id: nil
        configuration_mode: 'ApplyAndAutoCorrect'
        configuration_mode_frequency_mins: 30
        debug_mode: 'All'
        reboot_if_needed: false
        refresh_frequency_mins: 30
        refresh_mode: 'PUSH'

  - name: chef_with_powershell
    run_list:
    - recipe[demo::default]
  - name: chef_with_dsc_script
    run_list:
    - recipe[demo::dsc_script]
  - name: chef_with_dsc_resource
    excludes:
      - windows_2012r2_wmf4
    run_list:
    - recipe[demo::dsc_resource]
